export const data = [{
	 name 		: "Lonny Maclaren",
	 ip 		: "254.052.238.246",
	 location 	: "san marino",
	 flag 		: require("./images/flags/san-marino.svg"),
	 status 	: "Dead Fisherman",
	 time 		: "19:34",
},
{
	 name 		: "Maisha Mowers",
	 ip 		: "141.009.062.251",
	 location 	: "jordan",
	 flag 		: require("./images/flags/jordan.svg"),
	 status 	: "Red Angel",
	 time 		: "22:20",
},
{
	 name 		: "Gerald Martz",
	 ip 		: "069.121.136.224",
	 location 	: "switzerland",
	 flag 		: require("./images/flags/switzerland.svg"),
	 status 	: "Red Angel",
	 time 		: "22:13",
},
{
	 name 		: "Wilma Leffel",
	 ip 		: "095.026.137.238",
	 location 	: "azerbaijan",
	 flag 		: require("./images/flags/azerbaijan.svg"),
	 status 	: "White Gorilla",
	 time 		: "03:18",
},
{
	 name 		: "Cathy Heins",
	 ip 		: "243.156.028.234",
	 location 	: "nigeria",
	 flag 		: require("./images/flags/nigeria.svg"),
	 status 	: "White Gorilla",
	 time 		: "13:25",
},
{
	 name 		: "Dung Mennenga",
	 ip 		: "027.132.061.124",
	 location 	: "madagascar",
	 flag 		: require("./images/flags/madagascar.svg"),
	 status 	: "White Gorilla",
	 time 		: "01:22",
},
{
	 name 		: "Odis Punch",
	 ip 		: "233.224.141.091",
	 location 	: "sardinia",
	 flag 		: require("./images/flags/sardinia.svg"),
	 status 	: "White Gorilla",
	 time 		: "19:23",
},
{
	 name 		: "Sherice Bonelli",
	 ip 		: "080.054.121.084",
	 location 	: "belarus",
	 flag 		: require("./images/flags/belarus.svg"),
	 status 	: "Red Angel",
	 time 		: "03:60",
},
{
	 name 		: "Tabitha Robinett",
	 ip 		: "228.001.027.101",
	 location 	: "saint kitts and nevis",
	 flag 		: require("./images/flags/saint-kitts-and-nevis.svg"),
	 status 	: "Dead Fisherman",
	 time 		: "07:33",
},
{
	 name 		: "Cathy Heins",
	 ip 		: "247.031.245.021",
	 location 	: "haiti",
	 flag 		: require("./images/flags/haiti.svg"),
	 status 	: "Red Angel",
	 time 		: "16:28",
},
{
	 name 		: "Arletta Ye",
	 ip 		: "100.246.188.136",
	 location 	: "united arab emirates",
	 flag 		: require("./images/flags/united-arab-emirates.svg"),
	 status 	: "Dead Fisherman",
	 time 		: "12:48",
},
{
	 name 		: "Dwight Hornstein",
	 ip 		: "132.201.111.048",
	 location 	: "east timor",
	 flag 		: require("./images/flags/east-timor.svg"),
	 status 	: "Red Angel",
	 time 		: "10:07",
},
{
	 name 		: "Hannelore Ghent",
	 ip 		: "080.236.181.214",
	 location 	: "republic of the congo",
	 flag 		: require("./images/flags/republic-of-the-congo.svg"),
	 status 	: "Dead Fisherman",
	 time 		: "05:42",
},
{
	 name 		: "Deandre Lightford",
	 ip 		: "047.137.027.050",
	 location 	: "united kingdom",
	 flag 		: require("./images/flags/united-kingdom.svg"),
	 status 	: "White Gorilla",
	 time 		: "11:60",
},
{
	 name 		: "Dwight Hornstein",
	 ip 		: "216.002.135.195",
	 location 	: "ukraine",
	 flag 		: require("./images/flags/ukraine.svg"),
	 status 	: "Red Angel",
	 time 		: "05:47",
},
{
	 name 		: "Carole Kaczmarek",
	 ip 		: "058.239.005.001",
	 location 	: "kiribati",
	 flag 		: require("./images/flags/kiribati.svg"),
	 status 	: "Red Angel",
	 time 		: "11:31",
},
{
	 name 		: "Dwight Hornstein",
	 ip 		: "191.239.203.100",
	 location 	: "central african republic",
	 flag 		: require("./images/flags/central-african-republic.svg"),
	 status 	: "White Gorilla",
	 time 		: "17:55",
},
{
	 name 		: "Cathy Heins",
	 ip 		: "208.237.254.023",
	 location 	: "sao tome and prince",
	 flag 		: require("./images/flags/sao-tome-and-prince.svg"),
	 status 	: "Red Angel",
	 time 		: "13:18",
},
{
	 name 		: "Leonie Ly",
	 ip 		: "094.204.210.089",
	 location 	: "france",
	 flag 		: require("./images/flags/france.svg"),
	 status 	: "Red Angel",
	 time 		: "22:14",
},
{
	 name 		: "Janay Blasko",
	 ip 		: "081.033.158.180",
	 location 	: "bahamas",
	 flag 		: require("./images/flags/bahamas.svg"),
	 status 	: "Dead Fisherman",
	 time 		: "23:03",
}]
